version: "3.8"

services:
  terraform-local:
    build:
      context: .
      dockerfile: ./docker/terraform/dockerfile
    container_name: terraform-local
    tty: true
    volumes:
      - ./docker/terraform/.aws:/home/devuser/.aws
      - ./docker/terraform:/home/devuser/terraform
    env_file: ./docker/terraform/envfile
    working_dir: /home/devuser
