version: "3.8"

services:
  terraform-local:
    build:
      context: .
      dockerfile: ./docker/terraform/dockerfile
    container_name: terraform-local
    tty: true
    volumes:
      - ./docker/terraform/.aws:/root/.aws
      - .:/work
    env_file: ./docker/terraform/env/envfile
    working_dir: /work
